package pl.edu.pjatk.tau.dao;

import pl.edu.pjatk.tau.domain.Movie;

import java.sql.*;

public class MovieDaoJdbcImpl implements MovieDao {

    private Connection connection;
    private PreparedStatement addMovieStmt;


    public MovieDaoJdbcImpl() throws SQLException {
    }

    public MovieDaoJdbcImpl(Connection connection) throws SQLException {
        this.connection = connection;
        // if (!isDatabaseReady()) {
        //    createTables();
        //}

        setConnection(connection);
    }

    public void createTables() throws SQLException {
        connection.createStatement()
                .executeUpdate("CREATE TABLE " +
                        "Movie" +
                        "(id bigint GENERATED BY DEFAULT AS IDENTITY, " +
                        "title varchar(20) NOT NULL," +
                        "duration integer)");
    }

    private boolean isDatabaseReady() {
        try {
            ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
            boolean tableExists = false;
            while (rs.next()) {
                if ("Person".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
                    tableExists = true;
                    break;
                }
            }
            return tableExists;
        } catch (SQLException e) {
            return false;
        }
    }

    @Override
    public int addMovie(Movie movie) {
        int count = 0;
        try {
            addMovieStmt.setString(1, movie.getTitle());
            addMovieStmt.setInt(2, movie.getDuration());
            count = addMovieStmt.executeUpdate();
            ResultSet generatedKeys = addMovieStmt.getGeneratedKeys();
            if (generatedKeys.next()) {
                movie.setId(generatedKeys.getLong(1));
            }
        } catch (SQLException e) {
            throw new IllegalStateException(e.getMessage() + "\n" + e.getStackTrace().toString());
        }
        return count;
    }

    @Override
    public Connection getConnection() {
        return connection;
    }

    @Override
    public void setConnection(Connection connection) throws SQLException {
        this.connection = connection;
        addMovieStmt = connection.prepareStatement(
                "INSERT INTO Movie (title, duration) VALUES (?, ?)",
                Statement.RETURN_GENERATED_KEYS);
    }
}
